import type { Metadata } from "next";
import { Inter, Noto_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import icon1 from "/public/icon1.png";
import arrow from "/public/arrow.png";
import vector1 from "/public/vector1.svg";
import vector2 from "/public/vector2.svg";
import vector3 from "/public/vector3.svg";
import vector4 from "/public/vector4.svg";
import Link from "next/link";

const inter = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mirvracha-test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link className="link" href="/" legacyBehavior>
          <div className="wrapper">
            <Image className="bg-yellow" alt="yellow" src={vector3} fill />
            <Image className="bg-green" alt="green" src={vector2} fill />
            <Image className="bg-blue" alt="blue" src={vector1} fill />
            <main>
              <Image className="bg-blue1" alt="bg" src={vector4} />
              {children}
              <div className="about-title">
                <Image className="bg-blue2" alt="bg" src={vector4} />
                <h2>Терапия ХОБЛ: что в фокусе?</h2>
              </div>
              <div className="about">
                <p className="comment">
                  Даже 1 среднетяжелое обострение — сигнал к увеличению объема
                  терапии
                </p>
                <h3>
                  Приоритетные направления фармакотерапевтической стратегии при
                  ХОБЛ1:
                </h3>
                <div className="cards">
                  <div className="card">
                    <Image className="card__icon" src={icon1} alt="icon" />
                    <h4>
                      Ингаляционный <strong>антихолинергик</strong>
                    </h4>
                    <p>
                      Ингибирует бронхоконстрикторные эффекты ацетилхолина,
                      вступая с ним в конкурентный антагонизм за взаимодействие
                      с эффекторными мускариновыми рецепторами, дополняет и
                      потенцирует эффект β2-агонистов1
                    </p>
                  </div>
                  <div className="card">
                    <Image className="card__icon" src={icon1} alt="icon" />
                    <h4>
                      Ингаляционный <strong>β2-агонист</strong>
                    </h4>
                    <p>
                      Вызывает бронходилатацию посредством релаксации
                      гладкомышечных клеток бронхов независимо от характера
                      констриктивных стимулов, т. е. выступают в качестве
                      функциональных антагонистов бронхоконстрикции
                    </p>
                  </div>
                  <div className="card">
                    <Image className="card__icon" src={icon1} alt="icon" />
                    <h4>
                      Ингаляционный <strong>глюкокортикостероид</strong> (ИГКС)
                    </h4>
                    <p>
                      Снижает частоту обострений, особенно в сочетании с ДДБА,
                      подавляют хроническое воспаление при астме и снижают
                      гиперреактивность дыхательных путей
                    </p>
                  </div>
                </div>
                <div className="arrows">
                  <Image className="arrow" src={arrow} alt="arrow"></Image>
                  <Image className="arrow" src={arrow} alt="arrow"></Image>
                </div>
                <div className="advices">
                  <div className="card advice">
                    Пациентам с ХОБЛ рекомендуется комбинирование
                    бронходилататоров с разными механизмами действия; Назначение
                    2-х бронходилататоров из группы длительнодействующих
                    β2-агонистов (ДДБА) и длительнодействующих антихолинергиков
                    (ДДАХ), действие которых дополняет и усиливает друг друга1.
                  </div>
                  <div className="card advice">
                    Пациентам с ХОБЛ и частыми обострениями (≥2 среднетяжелых
                    обострений в течение 1 года/1 тяжелое обострение,
                    потребовавшее госпитализации) рекомендуется назначение ИГКС
                    в дополнение к ДДБА; Последние исследования показали, что
                    амбулаторное применение ИГКС/ДДБА у пациентов с ХОБЛ снижает
                    госпитальную летальность по сравнению с пациентами,
                    принимавшими только ДДБА (8,1% vs 13,2%)1.
                  </div>
                </div>
              </div>
            </main>
          </div>
        </Link>
      </body>
    </html>
  );
}
